version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    nunit3-console Tests\bin\Release\net452\Tests.dll
    dotnet test "Tests\Tests.csproj" --framework netcoreapp2.0 --configuration Release --no-build
artifacts:
- path: nugets\**\*.nupkg